# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\manuel.collongues\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\Mascaret\ui\ui_curve_selector_compare.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(618, 24)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cb_axe = QtWidgets.QComboBox(Form)
        self.cb_axe.setObjectName("cb_axe")
        self.horizontalLayout_2.addWidget(self.cb_axe)
        self.lbl_run = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_run.sizePolicy().hasHeightForWidth())
        self.lbl_run.setSizePolicy(sizePolicy)
        self.lbl_run.setObjectName("lbl_run")
        self.horizontalLayout_2.addWidget(self.lbl_run)
        self.cb_run = QtWidgets.QComboBox(Form)
        self.cb_run.setObjectName("cb_run")
        self.horizontalLayout_2.addWidget(self.cb_run)
        self.lbl_scen = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_scen.sizePolicy().hasHeightForWidth())
        self.lbl_scen.setSizePolicy(sizePolicy)
        self.lbl_scen.setObjectName("lbl_scen")
        self.horizontalLayout_2.addWidget(self.lbl_scen)
        self.cb_scen = QtWidgets.QComboBox(Form)
        self.cb_scen.setObjectName("cb_scen")
        self.horizontalLayout_2.addWidget(self.cb_scen)
        self.lbl_date_init = QtWidgets.QLabel(Form)
        self.lbl_date_init.setObjectName("lbl_date_init")
        self.horizontalLayout_2.addWidget(self.lbl_date_init)
        self.ctrl_date_init = QtWidgets.QDateTimeEdit(Form)
        self.ctrl_date_init.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1900, 1, 1), QtCore.QTime(0, 0, 0)))
        self.ctrl_date_init.setCalendarPopup(True)
        self.ctrl_date_init.setObjectName("ctrl_date_init")
        self.horizontalLayout_2.addWidget(self.ctrl_date_init)
        self.lbl_chart = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_chart.sizePolicy().hasHeightForWidth())
        self.lbl_chart.setSizePolicy(sizePolicy)
        self.lbl_chart.setObjectName("lbl_chart")
        self.horizontalLayout_2.addWidget(self.lbl_chart)
        self.cb_graph = QtWidgets.QComboBox(Form)
        self.cb_graph.setObjectName("cb_graph")
        self.horizontalLayout_2.addWidget(self.cb_graph)
        self.lbl_det = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_det.sizePolicy().hasHeightForWidth())
        self.lbl_det.setSizePolicy(sizePolicy)
        self.lbl_det.setObjectName("lbl_det")
        self.horizontalLayout_2.addWidget(self.lbl_det)
        self.cb_det = QtWidgets.QComboBox(Form)
        self.cb_det.setObjectName("cb_det")
        self.horizontalLayout_2.addWidget(self.cb_det)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_run.setText(_translate("Form", "Run"))
        self.lbl_scen.setText(_translate("Form", "Scen."))
        self.lbl_date_init.setText(_translate("Form", "Init."))
        self.ctrl_date_init.setDisplayFormat(_translate("Form", "dd/MM/yyyy HH:mm:ss"))
        self.lbl_chart.setText(_translate("Form", "Chart"))
        self.lbl_det.setText(_translate("Form", "_"))
