# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\manuel.collongues\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\Mascaret\ui\ui_interp_profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(293, 167)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb_message = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_message.setFont(font)
        self.lb_message.setObjectName("lb_message")
        self.verticalLayout.addWidget(self.lb_message)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.ch_autdisc = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ch_autdisc.setFont(font)
        self.ch_autdisc.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ch_autdisc.setChecked(True)
        self.ch_autdisc.setObjectName("ch_autdisc")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ch_autdisc)
        self.lb_disc = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_disc.setFont(font)
        self.lb_disc.setObjectName("lb_disc")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_disc)
        self.sp_nbplan = QtWidgets.QSpinBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sp_nbplan.setFont(font)
        self.sp_nbplan.setMinimum(1)
        self.sp_nbplan.setMaximum(999999999)
        self.sp_nbplan.setProperty("value", 100)
        self.sp_nbplan.setObjectName("sp_nbplan")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sp_nbplan)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.b_ok = QtWidgets.QDialogButtonBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.b_ok.setFont(font)
        self.b_ok.setOrientation(QtCore.Qt.Horizontal)
        self.b_ok.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.b_ok.setObjectName("b_ok")
        self.horizontalLayout.addWidget(self.b_ok)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.b_ok.accepted.connect(Dialog.accept)
        self.b_ok.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lb_message.setText(_translate("Dialog", "None"))
        self.ch_autdisc.setText(_translate("Dialog", "Automatic discretization"))
        self.lb_disc.setText(_translate("Dialog", " Discretization"))
