# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\manuel.collongues\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\Mascaret\ui\ui_import_res.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(573, 259)
        Form.setAcceptDrops(False)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.ed_scen = QtWidgets.QLineEdit(Form)
        self.ed_scen.setObjectName("ed_scen")
        self.gridLayout.addWidget(self.ed_scen, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.bt_path = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_path.sizePolicy().hasHeightForWidth())
        self.bt_path.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_path.setFont(font)
        self.bt_path.setObjectName("bt_path")
        self.gridLayout.addWidget(self.bt_path, 2, 2, 1, 1)
        self.txt_path = QtWidgets.QLineEdit(Form)
        self.txt_path.setObjectName("txt_path")
        self.gridLayout.addWidget(self.txt_path, 2, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonBox.setFont(font)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.ed_run = QtWidgets.QLineEdit(Form)
        self.ed_run.setObjectName("ed_run")
        self.gridLayout.addWidget(self.ed_run, 0, 1, 1, 1)
        self.mDateTimeEdit = QgsDateTimeEdit(Form)
        self.mDateTimeEdit.setTime(QtCore.QTime(18, 28, 38))
        self.mDateTimeEdit.setObjectName("mDateTimeEdit")
        self.gridLayout.addWidget(self.mDateTimeEdit, 3, 2, 1, 1)
        self.textEdit_com = QtWidgets.QTextEdit(Form)
        self.textEdit_com.setObjectName("textEdit_com")
        self.gridLayout.addWidget(self.textEdit_com, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Import Results"))
        self.label.setText(_translate("Form", "Run name : "))
        self.bt_path.setText(_translate("Form", "Model Path "))
        self.checkBox.setText(_translate("Form", "Initial Date"))
        self.label_2.setText(_translate("Form", "Scenario name : "))
        self.mDateTimeEdit.setDisplayFormat(_translate("Form", "dd/MM/yyyy HH:mm:ss.zz"))
        self.label_3.setText(_translate("Form", "Comments : "))
from qgsdatetimeedit import QgsDateTimeEdit
