# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\manuel.collongues\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\Mascaret\ui\scores\ui_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ui_score_select(object):
    def setupUi(self, ui_score_select):
        ui_score_select.setObjectName("ui_score_select")
        ui_score_select.resize(754, 531)
        self.gridLayout = QtWidgets.QGridLayout(ui_score_select)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(ui_score_select)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bt_clean = QtWidgets.QPushButton(ui_score_select)
        self.bt_clean.setObjectName("bt_clean")
        self.horizontalLayout.addWidget(self.bt_clean)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.tw_runs = QtWidgets.QTreeWidget(ui_score_select)
        self.tw_runs.setAutoFillBackground(False)
        self.tw_runs.setHeaderHidden(False)
        self.tw_runs.setObjectName("tw_runs")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tw_runs.headerItem().setFont(0, font)
        self.tw_runs.header().setVisible(True)
        self.tw_runs.header().setCascadingSectionResizes(True)
        self.tw_runs.header().setDefaultSectionSize(150)
        self.tw_runs.header().setHighlightSections(True)
        self.tw_runs.header().setMinimumSectionSize(31)
        self.tw_runs.header().setSortIndicatorShown(False)
        self.tw_runs.header().setStretchLastSection(True)
        self.verticalLayout_5.addWidget(self.tw_runs)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)

        self.retranslateUi(ui_score_select)
        QtCore.QMetaObject.connectSlotsByName(ui_score_select)

    def retranslateUi(self, ui_score_select):
        _translate = QtCore.QCoreApplication.translate
        ui_score_select.setWindowTitle(_translate("ui_score_select", "Form"))
        self.label_8.setText(_translate("ui_score_select", "Selection of the runs :"))
        self.bt_clean.setText(_translate("ui_score_select", "Clean"))
        self.tw_runs.headerItem().setText(0, _translate("ui_score_select", "Run"))
        self.tw_runs.headerItem().setText(1, _translate("ui_score_select", "Times"))
        self.tw_runs.headerItem().setText(2, _translate("ui_score_select", "Reference Time"))
        self.tw_runs.headerItem().setText(3, _translate("ui_score_select", "Comments"))
