# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\manuel.collongues\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\Mascaret\ui\ui_init_conc.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TracerLaws(object):
    def setupUi(self, TracerLaws):
        TracerLaws.setObjectName("TracerLaws")
        TracerLaws.resize(956, 604)
        self.gridLayout = QtWidgets.QGridLayout(TracerLaws)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cb_bief = QtWidgets.QComboBox(TracerLaws)
        self.cb_bief.setObjectName("cb_bief")
        self.horizontalLayout.addWidget(self.cb_bief)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 2, 1, 1)
        self.lay_graph_edit = QtWidgets.QVBoxLayout()
        self.lay_graph_edit.setObjectName("lay_graph_edit")
        self.gridLayout.addLayout(self.lay_graph_edit, 1, 2, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.b_import = QtWidgets.QPushButton(TracerLaws)
        self.b_import.setObjectName("b_import")
        self.verticalLayout_8.addWidget(self.b_import)
        self.line = QtWidgets.QFrame(TracerLaws)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_8.addWidget(self.line)
        self.b_add_line = QtWidgets.QPushButton(TracerLaws)
        self.b_add_line.setObjectName("b_add_line")
        self.verticalLayout_8.addWidget(self.b_add_line)
        self.b_delete_line = QtWidgets.QPushButton(TracerLaws)
        self.b_delete_line.setObjectName("b_delete_line")
        self.verticalLayout_8.addWidget(self.b_delete_line)
        self.gridLayout.addLayout(self.verticalLayout_8, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_LawWQ = QtWidgets.QLabel(TracerLaws)
        self.label_LawWQ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_LawWQ.setObjectName("label_LawWQ")
        self.horizontalLayout_4.addWidget(self.label_LawWQ)
        self.LawWQ = QtWidgets.QLineEdit(TracerLaws)
        self.LawWQ.setObjectName("LawWQ")
        self.horizontalLayout_4.addWidget(self.LawWQ)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.tab_laws = QtWidgets.QTableView(TracerLaws)
        self.tab_laws.setEnabled(True)
        self.tab_laws.setMinimumSize(QtCore.QSize(400, 0))
        self.tab_laws.setObjectName("tab_laws")
        self.tab_laws.horizontalHeader().setDefaultSectionSize(50)
        self.tab_laws.verticalHeader().setDefaultSectionSize(22)
        self.gridLayout.addWidget(self.tab_laws, 1, 1, 1, 1)
        self.b_OK_page2 = QtWidgets.QDialogButtonBox(TracerLaws)
        self.b_OK_page2.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.b_OK_page2.setObjectName("b_OK_page2")
        self.gridLayout.addWidget(self.b_OK_page2, 2, 2, 1, 1)
        self.actionB_import = QtWidgets.QAction(TracerLaws)
        self.actionB_import.setObjectName("actionB_import")
        self.actionB_addLine = QtWidgets.QAction(TracerLaws)
        self.actionB_addLine.setObjectName("actionB_addLine")
        self.actionB_delLine = QtWidgets.QAction(TracerLaws)
        self.actionB_delLine.setObjectName("actionB_delLine")
        self.actionB_OK_page2 = QtWidgets.QAction(TracerLaws)
        self.actionB_OK_page2.setObjectName("actionB_OK_page2")

        self.retranslateUi(TracerLaws)
        self.b_add_line.clicked.connect(self.actionB_addLine.trigger) # type: ignore
        self.b_delete_line.clicked.connect(self.actionB_delLine.trigger) # type: ignore
        self.b_import.clicked.connect(self.actionB_import.trigger) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TracerLaws)

    def retranslateUi(self, TracerLaws):
        _translate = QtCore.QCoreApplication.translate
        TracerLaws.setWindowTitle(_translate("TracerLaws", "Initial Concentration"))
        self.b_import.setText(_translate("TracerLaws", "Import"))
        self.b_add_line.setText(_translate("TracerLaws", "Add Line"))
        self.b_delete_line.setText(_translate("TracerLaws", "Delete Line"))
        self.label_LawWQ.setText(_translate("TracerLaws", "Initial Concentration Names :"))
        self.actionB_import.setText(_translate("TracerLaws", "b_import"))
        self.actionB_import.setToolTip(_translate("TracerLaws", "b_import"))
        self.actionB_addLine.setText(_translate("TracerLaws", "b_addLine"))
        self.actionB_addLine.setToolTip(_translate("TracerLaws", "b_addLine"))
        self.actionB_delLine.setText(_translate("TracerLaws", "b_delLine"))
        self.actionB_delLine.setToolTip(_translate("TracerLaws", "b_delLine"))
        self.actionB_OK_page2.setText(_translate("TracerLaws", "b_OK_page2"))
        self.actionB_OK_page2.setToolTip(_translate("TracerLaws", "b_OK_page2"))
