# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\manuel.collongues\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\Mascaret\ui\ui_export.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(476, 363)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_all_exp_res = QtWidgets.QCheckBox(Dialog)
        self.cb_all_exp_res.setObjectName("cb_all_exp_res")
        self.verticalLayout.addWidget(self.cb_all_exp_res)
        self.tw_runs = QtWidgets.QTreeWidget(Dialog)
        self.tw_runs.setAutoFillBackground(False)
        self.tw_runs.setHeaderHidden(False)
        self.tw_runs.setObjectName("tw_runs")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tw_runs.headerItem().setFont(0, font)
        self.tw_runs.header().setVisible(True)
        self.tw_runs.header().setCascadingSectionResizes(True)
        self.tw_runs.header().setDefaultSectionSize(300)
        self.tw_runs.header().setHighlightSections(True)
        self.tw_runs.header().setMinimumSectionSize(31)
        self.tw_runs.header().setSortIndicatorShown(False)
        self.tw_runs.header().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tw_runs)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.b_export = QtWidgets.QPushButton(Dialog)
        self.b_export.setObjectName("b_export")
        self.horizontalLayout.addWidget(self.b_export)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.b_cancel = QtWidgets.QPushButton(Dialog)
        self.b_cancel.setObjectName("b_cancel")
        self.horizontalLayout.addWidget(self.b_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Export Schema"))
        self.cb_all_exp_res.setText(_translate("Dialog", "Export all Results"))
        self.tw_runs.headerItem().setText(0, _translate("Dialog", "Run"))
        self.tw_runs.headerItem().setText(1, _translate("Dialog", "Times"))
        self.tw_runs.headerItem().setText(2, _translate("Dialog", "Comments"))
        self.b_export.setText(_translate("Dialog", "Export"))
        self.b_cancel.setText(_translate("Dialog", "Cancel"))
